name: CI

on:
  pull_request:
    branches: [main, master]
    types: [opened, synchronize, reopened, edited]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Install dependencies
      run: dotnet restore src/BlazorTenant/BlazorTenant.csproj
    - name: Build
      run: dotnet build --configuration Release --no-restore src/BlazorTenant/BlazorTenant.csproj
    - name: Test
      uses: zyborg/dotnet-tests-report@v1
      with:
        project_path: test/BlazorTenant.Tests
        report_name: blazor_tenant_tests
        report_title: Blazor Tenant Tests
        github_token: ${{ secrets.GITHUB_TOKEN }}
